name: Brandon Spaulding
favicon: null
layout_spectrum: 0.58227
typography_spectrum: 0.00474
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
