name: Brandon Spaulding
favicon: null
layout_spectrum: 0.20998059399425983
typography_spectrum: 0.9813686646521091
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.33579600928351283
  lightness: 0.0713316157925874
  saturation: 0.31632299604825675
  rhythmicContrast: 0.03835660847835243
purpose: []
