name: Brandon Spaulding
favicon: null
layout_spectrum: 0.73866
typography_spectrum: 0.10464
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#64a8de'
    - '#000000'
    - '#00ffff'
    - '#0000ff'
    - '#5555aa'
  brandStrength: 0.4375
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
